### ISSUE TITLE
osm2pgsql accepts multiple conflicting arguments

### ISSUE THREAD

**Issue by lonvia** [osm2pgsql-dev/osm2pgsql#142]
(moved here from https://trac.openstreetmap.org/ticket/2810)

by accident, I specified the -O twice, but got no warning. this is bad : ./osm2pgsql -O gazetteer -U gis -H localhost -lsc -O pgsql -C 2000 -d gisdb test.osm.bz2

osm2pgsql should check for duplicate and conflicting arguments, I can make a patch for this if needed.

mike

**Comment by pnorman** [comment]
Confirming this still happens. It would also be the case for `-l`/`-m`/`-E`, `-p`, `-d`, `-C` and plenty of other options.

Do we want to solve this? It might help with command-line mistakes.

**Comment by lonvia** [comment]
Yes, it would be nice to have.

**Comment by pnorman** [comment]
Perhaps we should move to boost::program_options or something which takes care of this for us? Otherwise, we're looking at adding checks to a dozen options.
