### ISSUE TITLE
Logging falsely suggests CLUSTER is run

### ISSUE THREAD

**Issue by mboeringa** [osm2pgsql-dev/osm2pgsql#1565]
## What version of osm2pgsql are you using?

osm2pgsql v1.5.1

## What operating system and PostgreSQL/PostGIS version are you using?

Ubuntu 20.04.1 LTS, PostgreSQL 13.4 / PostGIS 3.1.3

## What did you do exactly?

Monitored SQL statements generated by osm2pgsql in pgAdmin.

## What did you expect to happen?

Currently logging suggests **CLUSTER** is run in PostgreSQL, however, in reality an "**ORDER BY way**" statement is used. While the net result of these two options is virtually identical, the suggestion that CLUSTER is run has a side consequence. Any tables that are truly CLUSTERed, can be easily re-clustered using the PostgreSQL [clusterdb utility](https://www.postgresql.org/docs/current/app-clusterdb.html). This is not the case for tables spatially sorted by "ORDER BY way".

Maybe re-phrasing to a slightly more neutral statement like:

"Spatially sorting / optimizing table <X>"

would be better.

**Comment by joto** [comment]
I agree that we should change the docs here if we are not actually using `CLUSTER`. But maybe we should use it. Waaay back, osm2pgsql used `CLUSTER` and then switched away from it. Before changing the docs, we should re-check with modern database versions whether it still is better to not cluster.

**Comment by pnorman** [comment]
CLUSTER requires building an index twice so is generally slower
