### ISSUE TITLE
Huge performance loss when using --extra-atributes

### ISSUE THREAD

**Issue by boerngen-schmidt** [osm2pgsql-dev/osm2pgsql#189]
When importing data with osm2pgsql and the --extra-atributes switch is used the performance of reading the PBF file drops below a 10th of what it was than without using the extra-attributes switch.

Just for comparison:
- Before: 
  Node 2994 k/s, Way 52,54 k/s, Relations 710/s
- After:
  Node: 122 k/s, Way 22,54 k/s, Realtions  /s

I also tested the new C++ version from PL https://github.com/openstreetmap/osm2pgsql/pull/187 but having the same issue.

System is a Xeon-1231v3, 16GB Ram, SSD running Elementary OS (aka Ubuntu 14.10)

**Comment by mmd-osm** [comment]
This issue is very old, PBF parsing has moved to libosmium in the meantime, all code references mentioned in https://github.com/openstreetmap/osm2pgsql/issues/189#issuecomment-58274096 no longer exist.

Is this still relevant? Closing?

**Comment by lonvia** [comment]
Last time I checked there was still an anomaly that needed looking into.

**Comment by mmd-osm** [comment]
`osmdata_t::{node,way,relation}_add` only processes an object, if it has at least one tag. In case of nodes, more than 97% of all nodes don't have any tags and would be discarded right away. However, when providing the "Extra parameters" option, every single object needs to be processed. 

Depending on the output, this much larger amount of total data to be processed could make a difference: for the Flex backend, turning on extra attributes for a completely empty style file reduces throughput by about 50%.

I wonder if this should be reflected in docs/flex.md. At this time, the page says: 
> osm2pgsql.process_node(object): Called for each node.

There's no mentioning of a tag filter, or the role of the extra-attributes parameter. It's role is described as turning on/off meta data. That's unrelated to the question of the object having tags or not.
