### ISSUE TITLE
highway=rest_area treatet as line

### ISSUE THREAD

**Issue by reald** [osm2pgsql-dev/osm2pgsql#2116]
## What version of osm2pgsql are you using?

```
osm2pgsql version 1.10.0
Build: RelWithDebInfo
Compiled using the following library versions:
Libosmium 2.20.0
Proj [API 6] 8.2.1
Lua 5.3.6
```

## What operating system and PostgreSQL/PostGIS version are you using?

Ubuntu 22.04.3 LTS

## Tell us something about your system

32GB Ram, 16 Cores

## What did you do exactly?

Imported .pbf file:

 `osm2pgsql --slim --drop -C 8192 -c -S default.style -l -d $DBNAME -U real -H localhost -W germany-latest.osm.pbf`

## What did you expect to happen?

Closed lines with `highway='rest_area'` should appear in `planet_osm_polygon`.

## What did happen instead?

Closed lines with `highway='rest_area'` appeared in `planet_osm_line` and some in `planet_osm_polygon`.

## What did you do to try analyzing the problem?

Tried osm2pgsql version 1.6 and 1.10.0.

The difference seem to be that the entries in `planet_osm_polygon` have `area='yes'` set, too.

The problem is that setting `area='yes'` is unnecessary because `highway='rest_area'` already implicitly marks an area. josm gives a warning if you want wo set `area='yes'` together with `highway='rest_area'`.

=> Treat all closed lines with `highway='rest_area'` as areas/polygons independent if `area='yes'` is set or not.

**Comment by joto** [comment]
The `default.style` you are using is just a starting point for your configuration. It isn't possible for us to keep track of all OSM tags and whether they should be used as polygon or not. Also the config file is not enough to create that kind of setting, you also need to use the `style.lua`-type config file as described [here](https://osm2pgsql.org/doc/manual.html#lua-tag-transformations).

You can change the configuration to suite your needs. For a possibly more complete and up-to-date configuration have a look at the configuration that comes with [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto/).

Note that all these config files use the "old pgsql output". For new projects I recommend using the "new flex output", which allows much more flexible configuration. See the [Flex Output chapter in the manual](https://osm2pgsql.org/doc/manual.html#the-flex-output).

**Comment by pnorman** [comment]
You're using the C transforms, which we can't modify the behavior of and will be getting rid of in 2.0. The C transforms are known to have a number of issues, particularly around area, as areas must be defined on a key level, not a value level.
