### ISSUE TITLE
When Planet osm data import, way showing 0 and not started

### ISSUE THREAD

**Issue by erkanrua** [osm2pgsql-dev/osm2pgsql#2187]
![resim](https://github.com/osm2pgsql-dev/osm2pgsql/assets/4141463/ba0beccd-7a4b-4ac5-aaad-5587c92ad50c)

Processing: Node(5024220k 616.3k/s) Way(0k 0.00k/s) Relation(0 0.0/s) waiting more than 16 hours.

Server configuration;
vCpu: 6
Ram: 64 GB
Disk: 2 TB

**Comment by mboeringa** [comment]
Maybe unrelated, but while your PostgreSQL and osm2pgsql versions seem quite up to date, your PostGIS is still reported as 3.0. It is probably recommendable to upgrade it to the latest 3.4.

Your cache setting of 60000 also seems high considering only 64GB RAM.

**Comment by erkanrua** [comment]
I don't thing related version because I imported last week using by nominatim. Maybe depends of cache value , I decreased and retry it but it had node processing started from 0.
is it possible to contiune current process ? 

I will share after change cache setting to 30000 even if it works or not. 
Thank reply

**Comment by mboeringa** [comment]
Also note that the latest versions of osm2pgsql removed gazetteer output (https://github.com/osm2pgsql-dev/osm2pgsql/pull/2157/files), that historically was needed for Nominatim. You may need to update your Lua style file to flex output to have it work with the latest versions of osm2pgsql. See the manual also:
https://osm2pgsql.org/

**Comment by erkanrua** [comment]
But I am not using nominatim using just osm2pgsql script.

**Comment by joto** [comment]
When you open an issue there is a form shown that asks for all the information that we need to help you. You ignored that form. So we can not help you. At a minimum we need to know exactly the command line you are using and from where you got the data. You don't even mention which version of osm2pgsql you are using. And don't use screen shots, they are annoying and hard to read. I am closing this issue here, please open a new one and use the form.

**Comment by erkanrua** [comment]
Sorry for ignored form yeah you are right when run it osm2pgsl version you know firstly write it version actually I though osm2pgsl version read from the screenshot. I aggree with you sorry about that.

My osm2pgsl version is 1.11.0 also I solved that issue after for @mboeringa advice when I changed the cache value. In now processing ways so I passed other steps thank you. 

Sorry for about that.
