### ISSUE TITLE
cmake on ubuntu 22.04-lts requires libboost-dev, libboost-system-dev, libboost-filesystem-dev to be installed

### ISSUE THREAD

**Issue by mumins** [osm2pgsql-dev/osm2pgsql#2194]
## What version of osm2pgsql are you using?

2024-06-11 16:37:59  osm2pgsql version 1.11.0 (1.11.0)
Build: RelWithDebInfo
Compiled using the following library versions:
Libosmium 2.20.0
Proj [API 6] 8.2.1
Lua 5.3.6

## What operating system and PostgreSQL/PostGIS version are you using?
14.12 / 3.2.0

ubuntu 22_04-lts-gen2, Azure image 22.04.202405140

## Tell us something about your system

Azure virtual machine Standard D8ads v5 (8 vcpus, 32 GiB memory)

## What did you do exactly?

cmake

## What did you expect to happen?

Install instructions provide complete list of required libraries.

## What did happen instead?

cmake threw error messages
Could not find a package configuration file provided by "boost_system"
Could not find a package configuration file provided by "boost_filesystem"

## What did you do to try analyzing the problem?

Added libboost-system-dev, libboost-filesystem-dev to the list of required packages.
It fixed the issue.

Suggestion: update installation instructions.

**Comment by joto** [comment]
The README for the version 1.11.0 that you are using has both libboost-system-dev and libboost-filesystem-dev packages in the Debian/Ubuntu command line. So I believe this is correct. You might have been confused looking at the current master README which doesn't have these any more, because they are not needed any more.

**Comment by mumins** [comment]
You are right, I was looking into master README.
Thank you!
