### ISSUE TITLE
master CMakeLists.txt lists version as 1.11.0

### ISSUE THREAD

**Issue by jmckenna** [osm2pgsql-dev/osm2pgsql#2241]
- the `master` branch CMakeLists.txt lists the version as [1.11.0](https://github.com/osm2pgsql-dev/osm2pgsql/blob/master/CMakeLists.txt#L4)
- this causes confusion for packagers/users, building against master, and then the compiled tool (for a user) will return the version as 1.10.0 (which of course it is not, it is not the 1.11.0 release version)

Suggestion:
- change the master CMakeLists.txt version to something like `1.13.0-dev`, and then as part of your release process, modify that version to the official release value

**Comment by joto** [comment]
Packagers should not use master. And users know that they are using master and when build from the git repo the `--version` output will show somthing like `osm2pgsql version 1.11.0 (1.11.0-129-g770083d7)` making it clear that this is not the actual 1.11.0 but a specific git version based on 1.11.0. I think that's quite clear. And it doesn't require us to decide on a version number of the next version before that's ready.

**Comment by jmckenna** [comment]
@joto thanks, closing.
